import React, { useState, useEffect } from 'react';
import { User, UserRole } from '../types';
import { storageService } from '../services/storage';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Trash2, UserPlus, Save, Shield, User as UserIcon, Eye, AlertTriangle, Terminal, Lock } from 'lucide-react';
import { Modal } from '../components/ui/Modal';

interface AdminPanelProps {
  currentUser: User;
}

export const AdminPanel: React.FC<AdminPanelProps> = ({ currentUser }) => {
  const [users, setUsers] = useState<User[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  
  // Form State
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [fullName, setFullName] = useState('');
  const [role, setRole] = useState<UserRole>('user');

  // Error State
  const [showSchemaError, setShowSchemaError] = useState(false);

  // Super Admin Check
  const isSuperAdmin = currentUser.username === 'faisalhassan';

  const refreshUsers = async () => {
      const data = await storageService.getUsers();
      setUsers(data);
  };

  useEffect(() => {
    refreshUsers();
  }, []);

  const handleOpenCreate = () => {
    setEditingUser(null);
    setUsername('');
    setPassword('');
    setFullName('');
    setRole('user');
    setIsModalOpen(true);
  };

  const handleOpenEdit = (user: User) => {
    setEditingUser(user);
    setUsername(user.username);
    setPassword(user.password || '');
    setFullName(user.fullName);
    setRole(user.role);
    setIsModalOpen(true);
  };

  const handleDelete = async (userId: string) => {
    if (!isSuperAdmin) {
      alert("Only the Super Admin (faisalhassan) can delete users.");
      return;
    }
    if (window.confirm('Are you sure you want to delete this user?')) {
      await storageService.deleteUser(userId);
      await refreshUsers();
    }
  };

  const handleSave = async () => {
    if (!username || !fullName) return alert("All fields except password (if editing) are required");

    // Prevent non-superadmins from creating/promoting admins if we wanted to be very strict,
    // but the UI restriction below handles the visual part.
    // Here we just ensure data integrity.

    try {
        if (editingUser) {
          await storageService.updateUser({
            ...editingUser,
            username,
            fullName,
            role,
            password: password || editingUser.password
          });
        } else {
          if (!password) return alert("Password is required for new users");
          await storageService.createUser({
            id: '', // Generated by DB
            username,
            password,
            fullName,
            role
          });
        }
        await refreshUsers();
        setIsModalOpen(false);
    } catch (e: any) {
        console.error("Save User Error:", e);
        // Check for Postgres check violation (code 23514) or specific message content
        if (e.code === '23514' || (e.message && (e.message.includes('check constraint') || e.message.includes('users_role_check')))) {
            setShowSchemaError(true);
        } else {
            alert("Failed to save user: " + e.message);
        }
    }
  };

  const getRoleBadge = (role: UserRole) => {
    switch(role) {
      case 'admin': return 'bg-purple-100 text-purple-800';
      case 'mamdhoob': return 'bg-blue-100 text-blue-800';
      default: return 'bg-green-100 text-green-800';
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Admin User Management</h1>
          <p className="text-gray-500">Create, edit, and manage system users</p>
        </div>
        <Button onClick={handleOpenCreate}>
          <UserPlus className="h-5 w-5 mr-2" />
          Create New User
        </Button>
      </div>

      {!isSuperAdmin && (
          <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4">
              <div className="flex">
                  <div className="flex-shrink-0">
                      <Lock className="h-5 w-5 text-yellow-400" aria-hidden="true" />
                  </div>
                  <div className="ml-3">
                      <p className="text-sm text-yellow-700">
                          You are logged in as a standard administrator. <br/>
                          Deletion of users and role modifications are restricted to the Super Admin (<strong>faisalhassan</strong>).
                      </p>
                  </div>
              </div>
          </div>
      )}

      <div className="bg-white shadow-sm border border-gray-200 rounded-xl overflow-hidden">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">User</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Role</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Password (Visible)</th>
              <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {users.map(user => (
              <tr key={user.id} className="hover:bg-gray-50">
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="flex items-center">
                    <div className="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 flex items-center justify-center">
                        <UserIcon className="h-5 w-5 text-gray-500" />
                    </div>
                    <div className="ml-4">
                      <div className="text-sm font-medium text-gray-900">{user.fullName}</div>
                      <div className="text-sm text-gray-500">@{user.username}</div>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full capitalize ${getRoleBadge(user.role)}`}>
                    {user.role}
                  </span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 font-mono">
                  {user.password || '••••••'}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-2">
                  <button 
                    onClick={() => handleOpenEdit(user)}
                    className="text-primary-600 hover:text-primary-900"
                  >
                    Edit
                  </button>
                  {isSuperAdmin && user.username !== 'faisalhassan' && ( 
                    <button 
                      onClick={() => handleDelete(user.id)}
                      className="text-red-600 hover:text-red-900"
                    >
                      Delete
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* CREATE / EDIT USER MODAL */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingUser ? 'Edit User' : 'Create New User'}
        footer={
          <>
            <Button variant="secondary" onClick={() => setIsModalOpen(false)}>Cancel</Button>
            <Button onClick={handleSave}>Save User</Button>
          </>
        }
      >
        <div className="space-y-4">
          <Input 
            label="Full Name" 
            value={fullName} 
            onChange={e => setFullName(e.target.value)}
            placeholder="e.g. Sarah Connor"
          />
          <Input 
            label="Username" 
            value={username} 
            onChange={e => setUsername(e.target.value)}
            placeholder="e.g. sarahc"
            disabled={editingUser?.username === 'faisalhassan'}
          />
          <Input 
            label="Password" 
            value={password} 
            onChange={e => setPassword(e.target.value)}
            type="text"
            placeholder={editingUser ? "Leave blank to keep current" : "Enter password"}
          />
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
                Role 
                {!isSuperAdmin && <span className="text-xs text-orange-500 ml-2">(Locked: Super Admin Only)</span>}
            </label>
            <div className={`flex flex-col space-y-2 mt-2 ${!isSuperAdmin ? 'opacity-50 pointer-events-none grayscale' : ''}`}>
              <label className="flex items-center space-x-2 cursor-pointer p-2 border rounded-md hover:bg-gray-50">
                <input 
                  type="radio" 
                  name="role" 
                  value="admin" 
                  checked={role === 'admin'}
                  onChange={() => setRole('admin')}
                  disabled={editingUser?.username === 'faisalhassan' || !isSuperAdmin} 
                  className="text-primary-600 focus:ring-primary-500"
                />
                <div className="flex flex-col">
                  <span className="flex items-center font-medium text-sm text-gray-900"><Shield className="w-4 h-4 mr-1 text-purple-600"/> Administrator</span>
                  <span className="text-xs text-gray-500 ml-5">Full system access (Create, Edit, Delete)</span>
                </div>
              </label>

              <label className="flex items-center space-x-2 cursor-pointer p-2 border rounded-md hover:bg-gray-50">
                <input 
                  type="radio" 
                  name="role" 
                  value="mamdhoob" 
                  checked={role === 'mamdhoob'}
                  onChange={() => setRole('mamdhoob')}
                  disabled={!isSuperAdmin}
                  className="text-primary-600 focus:ring-primary-500"
                />
                <div className="flex flex-col">
                  <span className="flex items-center font-medium text-sm text-gray-900"><Eye className="w-4 h-4 mr-1 text-blue-600"/> Mamdhoob</span>
                  <span className="text-xs text-gray-500 ml-5">Can only mark voters as 'Voted'</span>
                </div>
              </label>

              <label className="flex items-center space-x-2 cursor-pointer p-2 border rounded-md hover:bg-gray-50">
                <input 
                  type="radio" 
                  name="role" 
                  value="user" 
                  checked={role === 'user'}
                  onChange={() => setRole('user')}
                  disabled={!isSuperAdmin}
                  className="text-primary-600 focus:ring-primary-500"
                />
                <div className="flex flex-col">
                  <span className="flex items-center font-medium text-sm text-gray-900"><UserIcon className="w-4 h-4 mr-1 text-green-600"/> Normal User</span>
                  <span className="text-xs text-gray-500 ml-5">Read-only access</span>
                </div>
              </label>
            </div>
          </div>
        </div>
      </Modal>

      {/* SCHEMA ERROR MODAL */}
      <Modal
        isOpen={showSchemaError}
        onClose={() => setShowSchemaError(false)}
        title="Database Update Required"
        footer={
            <Button onClick={() => setShowSchemaError(false)}>Close</Button>
        }
      >
          <div className="flex flex-col items-center justify-center p-2">
            <div className="bg-orange-100 p-3 rounded-full mb-4">
                <AlertTriangle className="h-8 w-8 text-orange-600" />
            </div>
            <h3 className="text-lg font-bold text-gray-900 mb-2">Constraint Violation Detected</h3>
            <p className="text-sm text-gray-600 text-center mb-4">
                The allowed roles in your database need to be updated. <br/>
                <strong>Clear your Supabase SQL Editor first</strong>, then paste and run the code below:
            </p>
            
            <div className="bg-gray-800 rounded-md p-4 w-full relative group">
                <div className="absolute top-2 right-2 text-xs text-gray-400 flex items-center">
                    <Terminal className="w-3 h-3 mr-1" /> SQL
                </div>
                <code className="text-xs text-green-400 whitespace-pre-wrap break-all font-mono">
{`-- 1. Clear your SQL Editor window
-- 2. Paste and Run this:

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin', 'user', 'mamdhoob'));`}
                </code>
            </div>
          </div>
      </Modal>
    </div>
  );
};