import React, { useState, useEffect } from 'react';
import { User, UserRole } from '../types';
import { storageService } from '../services/storage';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Trash2, UserPlus, Save, Shield, User as UserIcon } from 'lucide-react';
import { Modal } from '../components/ui/Modal';

export const AdminPanel: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  
  // Form State
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [fullName, setFullName] = useState('');
  const [role, setRole] = useState<UserRole>('user');

  const refreshUsers = async () => {
      const data = await storageService.getUsers();
      setUsers(data);
  };

  useEffect(() => {
    refreshUsers();
  }, []);

  const handleOpenCreate = () => {
    setEditingUser(null);
    setUsername('');
    setPassword('');
    setFullName('');
    setRole('user');
    setIsModalOpen(true);
  };

  const handleOpenEdit = (user: User) => {
    setEditingUser(user);
    setUsername(user.username);
    setPassword(user.password || '');
    setFullName(user.fullName);
    setRole(user.role);
    setIsModalOpen(true);
  };

  const handleDelete = async (userId: string) => {
    if (window.confirm('Are you sure you want to delete this user?')) {
      await storageService.deleteUser(userId);
      await refreshUsers();
    }
  };

  const handleSave = async () => {
    if (!username || !fullName) return alert("All fields except password (if editing) are required");

    try {
        if (editingUser) {
          await storageService.updateUser({
            ...editingUser,
            username,
            fullName,
            role,
            password: password || editingUser.password
          });
        } else {
          if (!password) return alert("Password is required for new users");
          await storageService.createUser({
            id: '', // Generated by DB
            username,
            password,
            fullName,
            role
          });
        }
        await refreshUsers();
        setIsModalOpen(false);
    } catch (e) {
        alert("Failed to save user.");
        console.error(e);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Admin User Management</h1>
          <p className="text-gray-500">Create, edit, and manage system users</p>
        </div>
        <Button onClick={handleOpenCreate}>
          <UserPlus className="h-5 w-5 mr-2" />
          Create New User
        </Button>
      </div>

      <div className="bg-white shadow-sm border border-gray-200 rounded-xl overflow-hidden">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">User</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Role</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Password (Visible)</th>
              <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {users.map(user => (
              <tr key={user.id} className="hover:bg-gray-50">
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="flex items-center">
                    <div className="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 flex items-center justify-center">
                        <UserIcon className="h-5 w-5 text-gray-500" />
                    </div>
                    <div className="ml-4">
                      <div className="text-sm font-medium text-gray-900">{user.fullName}</div>
                      <div className="text-sm text-gray-500">@{user.username}</div>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${user.role === 'admin' ? 'bg-purple-100 text-purple-800' : 'bg-green-100 text-green-800'}`}>
                    {user.role}
                  </span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 font-mono">
                  {user.password || '••••••'}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-2">
                  <button 
                    onClick={() => handleOpenEdit(user)}
                    className="text-primary-600 hover:text-primary-900"
                  >
                    Edit
                  </button>
                  {user.username !== 'faisalhassan' && ( // Prevent deleting main admin
                    <button 
                      onClick={() => handleDelete(user.id)}
                      className="text-red-600 hover:text-red-900"
                    >
                      Delete
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingUser ? 'Edit User' : 'Create New User'}
        footer={
          <>
            <Button variant="secondary" onClick={() => setIsModalOpen(false)}>Cancel</Button>
            <Button onClick={handleSave}>Save User</Button>
          </>
        }
      >
        <div className="space-y-4">
          <Input 
            label="Full Name" 
            value={fullName} 
            onChange={e => setFullName(e.target.value)}
            placeholder="e.g. Sarah Connor"
          />
          <Input 
            label="Username" 
            value={username} 
            onChange={e => setUsername(e.target.value)}
            placeholder="e.g. sarahc"
            disabled={editingUser?.username === 'faisalhassan'}
          />
          <Input 
            label="Password" 
            value={password} 
            onChange={e => setPassword(e.target.value)}
            type="text"
            placeholder={editingUser ? "Leave blank to keep current" : "Enter password"}
          />
          
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Role</label>
            <div className="flex space-x-4 mt-2">
              <label className="flex items-center space-x-2 cursor-pointer">
                <input 
                  type="radio" 
                  name="role" 
                  value="user" 
                  checked={role === 'user'}
                  onChange={() => setRole('user')}
                  className="text-primary-600 focus:ring-primary-500"
                />
                <span className="flex items-center"><UserIcon className="w-4 h-4 mr-1"/> User</span>
              </label>
              <label className="flex items-center space-x-2 cursor-pointer">
                <input 
                  type="radio" 
                  name="role" 
                  value="admin" 
                  checked={role === 'admin'}
                  onChange={() => setRole('admin')}
                  disabled={editingUser?.username === 'faisalhassan'} 
                  className="text-primary-600 focus:ring-primary-500"
                />
                <span className="flex items-center"><Shield className="w-4 h-4 mr-1"/> Admin</span>
              </label>
            </div>
          </div>
        </div>
      </Modal>
    </div>
  );
};